### ISSUE TITLE
CI broken

### ISSUE THREAD

**Issue by rom1504** [PrismarineJS/node-minecraft-packets#19]
due to https://github.com/PrismarineJS/node-minecraft-packets/pull/18
please fix @u9g

**Comment by u9g** [comment]
Not my fault https://github.com/PrismarineJS/node-minecraft-packets/runs/3326596922?check_suite_focus=true#step:5:19 , this is due to prismarine-auth

**Comment by rom1504** [comment]
indeed, moved to https://github.com/PrismarineJS/prismarine-auth/issues/10
